
(1,"Tâm Lý - Kỹ Năng Sống","https://sachvui.com/the-loai/tam-ly-ky-nang-song.html",1),
 (3,"Marketing - Bán hàng ","https://sachvui.com/the-loai/marketing-ban-hang.html",1),
 (4,"Y Học - Sức Khỏe","https://sachvui.com/the-loai/y-hoc-suc-khoe.html",1),
 (5,"Học Ngoại Ngữ","https://sachvui.com/the-loai/sach-hoc-ngoai-ngu.html",1),
 (6,"Khoa Học - Kỹ Thuật","https://sachvui.com/the-loai/khoa-hoc-ky-thuat.html",1),
 (7,"Thể Thao - Nghệ Thuật","https://sachvui.com/the-loai/the-thao-nghe-thuat.html",1),
 (8,"Trinh Thám - Hình Sự","https://sachvui.com/the-loai/trinh-tham-hinh-su.html",1),
 (9,"Văn Hóa - Tôn Giáo","https://sachvui.com/the-loai/van-hoa-ton-giao.html",1),
 (10,"Tử Vi - Phong Thủy","https://sachvui.com/the-loai/tu-vi-phong-thuy.html",1),
 (11,"Lịch Sử - Chính Trị","https://sachvui.com/the-loai/lich-su-chinh-tri.html",1),
 (12,"Văn Học Việt Nam","https://sachvui.com/the-loai/van-hoc-viet-nam.html",1),
 (13,"Truyện Ngắn - Ngôn Tình","https://sachvui.com/the-loai/truyen-ngan-ngon-tinh.html",1),
 (14,"Truyện Cười - Tiếu Lâm","https://sachvui.com/the-loai/truyen-cuoi-tieu-lam.html",1),
 (15,"Tiểu Thuyết Phương Tây","https://sachvui.com/the-loai/tieu-thuyet-nuoc-ngoai.html",1),
 (16,"Truyện Ma - Truyện Kinh Dị","https://sachvui.com/the-loai/kinh-di-ma-quai.html",1),
 (17,"Huyền bí - Giả Tưởng","https://sachvui.com/the-loai/huyen-bi-gia-tuong.html",1),
 (18,"Hồi Ký - Tuỳ Bút","https://sachvui.com/the-loai/hoi-ki-tuy-but.html",1),
 (19,"Phiêu Lưu - Mạo Hiểm","https://sachvui.com/the-loai/phuu-luu-mao-hiem.html",1),
 (20,"Truyên Teen - Tuổi Học Trò","https://sachvui.com/the-loai/tuoi-hoc-tro.html",1),
 (21,"Cổ Tích - Thần Thoại","https://sachvui.com/the-loai/co-tich-than-thoai.html",1),
 (22,"Triết Học","https://sachvui.com/the-loai/triet-hoc.html",1),
 (23,"Kiếm Hiệp - Tiên Hiệp","https://sachvui.com/the-loai/kiem-hiep.html",1),
 (24,"Tiểu Thuyết Trung Quốc","https://sachvui.com/the-loai/tieu-thuyet-trung-quoc.html",1),
 (25,"Kiến Trúc - Xây Dựng","https://sachvui.com/the-loai/kien-truc-xay-dung.html",0),
 (26,"Nông - Lâm - Ngư","https://sachvui.com/the-loai/nong-lam-ngu.html",0),
 (27,"Công Nghệ Thông Tin","https://sachvui.com/the-loai/cong-nghe-thong-tin.html",0),
 (28,"Tài Liệu Học Tập","https://sachvui.com/the-loai/tai-lieu-on-thi.html",0),
 (29,"Ẩm thực - Nấu ăn","https://sachvui.com/the-loai/am-thuc-hoc-nau-an.html",0),
 (30,"Thư Viện Pháp Luật","https://sachvui.com/the-loai/thu-vien-phap-luat.html",0),
 (31,"Truyện Tranh","https://sachvui.com/the-loai/doc-truyen-tranh-online.html",0);

